default:
  adapter: mysql2
  charset: utf8mb4
  collation: utf8mb4_bin
  encoding: utf8mb4
  pool: 1
  username: <%= ENV.fetch("DATABASE_USER") { 'root' } %>
  password: <%= ENV.fetch("DATABASE_PASS") { '' } %>
  database: <%= ENV.fetch("DATABASE_NAME") { 'localhost_active_record_test' } %>
  socket: /tmp/mysql.sock

